services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - /home/gary/pyriteview:/var/www/html
      - /home/gary/pyriteview/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
   # command: /bin/sh -c "nginx -g 'daemon off;'"


  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_MODE=${APP_MODE:-development}
    image: php:7.4-fpm
    container_name: php-app
    user: "1000:1000"
    volumes:
      - /home/gary/pyriteview:/var/www/html
      - /home/gary/pyritephp:/var/www/html/vendor/gflauder/pyritephp
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini

    environment:
      - APP_MODE=${APP_MODE:-development}
      - PHP_SENDMAIL_PATH="/usr/sbin/sendmail -S mailpit:1025 -fsender@example.com"
    networks:
      - app-network

  # Mailpit service
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge